Algoritmo "Ex-PARA"
// 1) Desenvolver um programa que apresente todos os valores numéricos
// inteiros impares situados na faixa de 1000 ate 1500
Var
// Seção de Declarações das variáveis
contador: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...

para contador de 1000 ate 1500 passo 1 faca
    se ( contador % 2 = 1 ) entao
       escreval ( contador )
    fimse
fimpara

Fimalgoritmo