Algoritmo "Lista5.1_2"
//  Desenvolver um programa que exiba os números em ordem decrescente de 100
//até 1


Var
// Seção de Declarações das variáveis 

a : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
a <- 100

// se a <> 2 entao
//   escreva("Abululu")
//senao
//     escreva("Bilululu")
//fimse

enquanto a >= 1 faca
         //se a % 2 = 0 entao
            escreva(a)
         //fimse
         a <- a - 1
fimenquanto


Fimalgoritmo