Algoritmo "Lista5.1_3"
//  Desenvolver um programa que apresente os quadrados dos números inteiros
// de 15 a 200.

Var
// Seção de Declarações das variáveis 

a : real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...

// se a <> 2 entao
//   escreva("Abululu")
//senao
//     escreva("Bilululu")
//fimse
//enquanto  faca
         //se a % 2 = 0 entao
         //   escreva
         //fimse

fimenquanto


Fimalgoritmo