Algoritmo "lista2.1_1"
//Desenvolver um programa que pergunte ao usuário o seu nome completo e seu
//sexo. Em seguida, o programa deve apresentar os dados anteriormente
//informados.


Var
// Seção de Declarações das variáveis
   nome, sexo: caractere


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
           escreva("Informe seu Nome Completo :")
           leia (nome)
           escreva ("Informe seu  :")
           leia (nome)

Fimalgoritmo